[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[window]
padding = { x = 15, y = 15 }
dynamic_padding = true

opacity = 0.85
blur = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

[terminal]
shell = "/usr/bin/fish"
